"""empty message

Revision ID: 17260e649429
Revises: 93b90cbb134f
Create Date: 2023-12-21 15:30:29.159288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17260e649429'
down_revision = '93b90cbb134f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
